// Code generated by sqlc. DO NOT EDIT.
// source: duels.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const confirmDuel = `-- name: ConfirmDuel :exec
UPDATE duels
SET confirmed_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) ConfirmDuel(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, confirmDuel, id)
	return err
}

const createUnconfirmedDuel = `-- name: CreateUnconfirmedDuel :exec
INSERT INTO duels (
    league_id,
    user_1_id,
    user_2_id,
    deck_1_id,
    deck_2_id,
    result,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateUnconfirmedDuelParams struct {
	LeagueID  sql.NullInt32 `json:"league_id"`
	User1ID   string        `json:"user_1_id"`
	User2ID   string        `json:"user_2_id"`
	Deck1ID   int32         `json:"deck_1_id"`
	Deck2ID   int32         `json:"deck_2_id"`
	Result    int32         `json:"result"`
	CreatedBy int32         `json:"created_by"`
}

func (q *Queries) CreateUnconfirmedDuel(ctx context.Context, arg CreateUnconfirmedDuelParams) error {
	_, err := q.db.ExecContext(ctx, createUnconfirmedDuel,
		arg.LeagueID,
		arg.User1ID,
		arg.User2ID,
		arg.Deck1ID,
		arg.Deck2ID,
		arg.Result,
		arg.CreatedBy,
	)
	return err
}

const deleteDuel = `-- name: DeleteDuel :exec
UPDATE duels
SET deleted_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteDuel(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteDuel, id)
	return err
}

const getDuel = `-- name: GetDuel :one
SELECT id, league_id, user_1_id, user_2_id, deck_1_id, deck_2_id, result, created_at, created_by, confirmed_at, deleted_at
FROM duels
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) GetDuel(ctx context.Context, id int32) (Duel, error) {
	row := q.db.QueryRowContext(ctx, getDuel, id)
	var i Duel
	err := row.Scan(
		&i.ID,
		&i.LeagueID,
		&i.User1ID,
		&i.User2ID,
		&i.Deck1ID,
		&i.Deck2ID,
		&i.Result,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ConfirmedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDuelsWithLimit = `-- name: ListDuelsWithLimit :many
SELECT
    id,
    league_id,
    user_1_id,
    user_2_id,
    deck_1_id,
    deck_2_id,
    result,
    created_at
FROM duels
WHERE confirmed_at IS NOT NULL
    AND deleted_at IS NULL
ORDER BY created_at
LIMIT $1
`

type ListDuelsWithLimitRow struct {
	ID        int32         `json:"id"`
	LeagueID  sql.NullInt32 `json:"league_id"`
	User1ID   string        `json:"user_1_id"`
	User2ID   string        `json:"user_2_id"`
	Deck1ID   int32         `json:"deck_1_id"`
	Deck2ID   int32         `json:"deck_2_id"`
	Result    int32         `json:"result"`
	CreatedAt time.Time     `json:"created_at"`
}

func (q *Queries) ListDuelsWithLimit(ctx context.Context, limit int32) ([]ListDuelsWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, listDuelsWithLimit, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDuelsWithLimitRow
	for rows.Next() {
		var i ListDuelsWithLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.User1ID,
			&i.User2ID,
			&i.Deck1ID,
			&i.Deck2ID,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedDuelsByUser = `-- name: ListUnconfirmedDuelsByUser :many
SELECT
    dl1.id,
    dl1.league_id,
    dl1.user_2_id AS opponent_user_id,
    dl1.deck_1_id AS deck_id,
    dl1.deck_2_id AS opponent_deck_id,
    (SELECT
        CASE
            WHEN dl1.result = -1 THEN '-'
            WHEN dl1.result = 0 THEN 'draw'
            WHEN dl1.result = 1 THEN 'win'
            WHEN dl1.result = 2 THEN 'lose'
            ELSE 'undefined'
        END
    ) AS result,
    dl1.created_at,
    dl1.created_by
FROM duels dl1
WHERE dl1.user_1_id = $1
    AND dl1.confirmed_at IS NULL
    AND dl1.deleted_at IS NULL
    AND (dl1.created_by = 1 OR dl1.created_by = 2)
UNION
SELECT
    dl2.id,
    dl2.league_id,
    dl2.user_1_id AS opponent_user_id,
    dl2.deck_2_id AS deck_id,
    dl2.deck_1_id AS opponent_deck_id,
    (SELECT
        CASE
            WHEN dl2.result = -1 THEN '-'
            WHEN dl2.result = 0 THEN 'draw'
            WHEN dl2.result = 1 THEN 'lose'
            WHEN dl2.result = 2 THEN 'win'
            ELSE 'undefined'
        END
    ) AS result,
    dl2.created_at,
    dl2.created_by
FROM duels dl2
WHERE dl2.user_2_id = $1
    AND dl2.confirmed_at IS NULL
    AND dl2.deleted_at IS NULL
    AND (dl2.created_by = 1 OR dl2.created_by = 2)
ORDER BY created_at
`

type ListUnconfirmedDuelsByUserRow struct {
	ID             int32         `json:"id"`
	LeagueID       sql.NullInt32 `json:"league_id"`
	OpponentUserID string        `json:"opponent_user_id"`
	DeckID         int32         `json:"deck_id"`
	OpponentDeckID int32         `json:"opponent_deck_id"`
	Result         interface{}   `json:"result"`
	CreatedAt      time.Time     `json:"created_at"`
	CreatedBy      int32         `json:"created_by"`
}

func (q *Queries) ListUnconfirmedDuelsByUser(ctx context.Context, user1ID string) ([]ListUnconfirmedDuelsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedDuelsByUser, user1ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnconfirmedDuelsByUserRow
	for rows.Next() {
		var i ListUnconfirmedDuelsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.LeagueID,
			&i.OpponentUserID,
			&i.DeckID,
			&i.OpponentDeckID,
			&i.Result,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
